version: "3.9"

services:
  monitordb:
    container_name: monitoringDB
    build:
      context: .
      dockerfile: dockerfilePGAdmin
    ports:
      - "9991:80"
    networks:
      - postgres

  serverdb: #Это имя хоста - по нему подключаемся из pgAdmin
    container_name: ordedDB
    build:
      context: .
      dockerfile: dockerfilePostgres
    ports:
      - "5432:5432"
    networks:
      - postgres
#...и еще по контейнеру каждому сервису под разные порты:)

networks:
  postgres:
    driver: bridge