FROM openjdk
ENV LC_ALL C.UTF-8
RUN mkdir /orderservice
COPY target/Orderservice-0.0.1-SNAPSHOT.jar /orderservice
WORKDIR /orderservice
ENV PATH=${PATH}:/orderservice
#Start APP in docker-compose
CMD java -jar Orderservice-0.0.1-SNAPSHOT.jar